services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - hertz
    networks:
      - app-network

  hertz:
    build:
      context: ./hertz
      dockerfile: Dockerfile
    container_name: hertz-api
    ports:
      - "8080:8080"
    networks:
      - app-network

  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: appdb
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    volumes:
      - data:/var/lib/mysql
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-cache
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: app-frontend
    networks:
      - app-network

volumes:
  data:

networks:
  app-network:
    driver: bridge
